### ISSUE TITLE
Repo cleanup...

### ISSUE THREAD

**Issue by dacb** [nicolepanek/Extremophile-protein-classification#5]
I see some files like [__pycache__](https://github.com/nicolepanek/ThermoDrift/tree/main/__pycache__) that should probably be cleaned up.  Also make sure your .gitignore is setup properly.

**Comment by achazingray** [comment]
@dacb just fixed the pycache issue

**Comment by achazingray** [comment]
What do you mean about the .gitignore tho?

**Comment by dacb** [comment]
If the `__pycache__` file is committed it might mean your `.gitignore` file is not complete enough to avoid this.  It could also be that the file was created before you current `.gitignore` was in place and was just left over.

**Comment by dacb** [comment]
Oh, I assumed that the `__pycache__` was allowed by your current `.gitignore`.  Maybe add `__pycache__/*` to your git ignore if it isn't already there to prevent it from coming back in the future.

**Comment by achazingray** [comment]
Done!
